import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '/MonkeyCodeReverseEngineer/',
  title: 'MonkeyCode的逆向分析',
  description: 'MonkeyCode的逆向分析',
  lang: 'zh-CN',
  lastUpdated: true,
  ignoreDeadLinks: true,
  markdown: {
    lineNumbers: true,
  },
  themeConfig: {
    search: {
      provider: 'local',
    },
    nav: [
      { text: '文档首页', link: '/' },
      { text: 'GitHub', link: 'https://github.com/vibe-coding-labs/MonkeyCodeReverseEngineer' },
    ],
    sidebar: [
          { text: "MonkeyCode的逆向分析", items: [
            { text: "首页", link: "/" },
            { text: "01-system-overview", link: "/01-architecture/01-system-overview" },
            { text: "02-data-flow", link: "/01-architecture/02-data-flow" },
            { text: "03-component-layer", link: "/01-architecture/03-component-layer" },
            { text: "04-error-handling-patterns", link: "/01-architecture/04-error-handling-patterns" },
            { text: "第一章：系统架构", link: "/01-architecture/README" },
            { text: "01-session-storage", link: "/02-auth/01-session-storage" },
            { text: "02-captcha-system", link: "/02-auth/02-captcha-system" },
            { text: "03-login-methods", link: "/02-auth/03-login-methods" },
            { text: "04-oauth-baizhi-cloud", link: "/02-auth/04-oauth-baizhi-cloud" },
            { text: "05-auth-middleware", link: "/02-auth/05-auth-middleware" },
            { text: "06-password-management", link: "/02-auth/06-password-management" },
            { text: "07-auth-automation", link: "/02-auth/07-auth-automation" },
            { text: "08-pool-gap-analysis", link: "/02-auth/08-pool-gap-analysis" },
            { text: "第二章：认证协议", link: "/02-auth/README" },
            { text: "01-model-management-api", link: "/03-llm/01-model-management-api" },
            { text: "02-interface-types", link: "/03-llm/02-interface-types" },
            { text: "03-provider-list", link: "/03-llm/03-provider-list" },
            { text: "04-model-pricing-quota", link: "/03-llm/04-model-pricing-quota" },
            { text: "05-llm-integration", link: "/03-llm/05-llm-integration" },
            { text: "06-coding-agent-config", link: "/03-llm/06-coding-agent-config" },
            { text: "06-private-model-creation", link: "/03-llm/06-private-model-creation" },
            { text: "07-model-discovery-pipeline", link: "/03-llm/07-model-discovery-pipeline" },
            { text: "第三章：LLM 通信协议", link: "/03-llm/README" },
            { text: "01-task-stream", link: "/04-websocket/01-task-stream" },
            { text: "02-task-control", link: "/04-websocket/02-task-control" },
            { text: "03-terminal", link: "/04-websocket/03-terminal" },
            { text: "04-tasklive-internal", link: "/04-websocket/04-tasklive-internal" },
            { text: "05-speech-to-text", link: "/04-websocket/05-speech-to-text" },
            { text: "06-acp-event-reference", link: "/04-websocket/06-acp-event-reference" },
            { text: "07-conversation-lifecycle", link: "/04-websocket/07-conversation-lifecycle" },
            { text: "第四章：WebSocket 协议", link: "/04-websocket/README" },
            { text: "01-endpoint-catalog", link: "/05-api/01-endpoint-catalog" },
            { text: "02-authorization-matrix", link: "/05-api/02-authorization-matrix" },
            { text: "03-conversation-api", link: "/05-api/03-conversation-api" },
            { text: "04-subscription-billing", link: "/05-api/04-subscription-billing" },
            { text: "05-admin-management-api", link: "/05-api/05-admin-management-api" },
            { text: "第五章：API 端点和授权", link: "/05-api/README" },
            { text: "01-architecture", link: "/06-vm-taskflow/01-architecture" },
            { text: "02-vm-lifecycle", link: "/06-vm-taskflow/02-vm-lifecycle" },
            { text: "03-mcp-protocol", link: "/06-vm-taskflow/03-mcp-protocol" },
            { text: "04-agent-internals", link: "/06-vm-taskflow/04-agent-internals" },
            { text: "05-resource-management", link: "/06-vm-taskflow/05-resource-management" },
            { text: "第六章：VM & TaskFlow", link: "/06-vm-taskflow/README" },
            { text: "01-architecture", link: "/07-proxy/01-architecture" },
            { text: "02-account-pool", link: "/07-proxy/02-account-pool" },
            { text: "03-multi-turn-conversation", link: "/07-proxy/03-multi-turn-conversation" },
            { text: "04-acp-to-openai-mapping", link: "/07-proxy/04-acp-to-openai-mapping" },
            { text: "05-oauth-automation", link: "/07-proxy/05-oauth-automation" },
            { text: "06-browser-fingerprinting", link: "/07-proxy/06-browser-fingerprinting" },
            { text: "06-oauth-automation-http", link: "/07-proxy/06-oauth-automation-http" },
            { text: "07-deployment-infrastructure", link: "/07-proxy/07-deployment-infrastructure" },
            { text: "08-server-startup", link: "/07-proxy/08-server-startup" },
            { text: "09-error-handling-deep", link: "/07-proxy/09-error-handling-deep" },
            { text: "09-oauth-http-automation-deep", link: "/07-proxy/09-oauth-http-automation-deep" },
            { text: "第七章：代理实现", link: "/07-proxy/README" },
            { text: "第八章：分析轮次", link: "/08-analysis-rounds/README" },
            { text: "round-01-to-06", link: "/08-analysis-rounds/rounds/round-01-to-06" },
            { text: "round-07-to-12", link: "/08-analysis-rounds/rounds/round-07-to-12" },
            { text: "round-13-to-18", link: "/08-analysis-rounds/rounds/round-13-to-18" },
            { text: "summary-report", link: "/08-analysis-rounds/summary-report" },
            { text: "02-proxy-security-analysis", link: "/09-security/02-proxy-security-analysis" },
            { text: "第九章：安全分析", link: "/09-security/README" },
            { text: "baizhi-security-report", link: "/09-security/baizhi-security-report" },
            { text: "01-asar-analysis", link: "/10-appendices/01-asar-analysis" },
            { text: "02-error-codes", link: "/10-appendices/02-error-codes" },
            { text: "03-environment-variables", link: "/10-appendices/03-environment-variables" },
            { text: "04-glossary", link: "/10-appendices/04-glossary" },
            { text: "05-code-exhibits", link: "/10-appendices/05-code-exhibits" },
            { text: "关键 API 请求/响应载荷示例", link: "/10-appendices/06-api-payloads" },
            { text: "WebSocket 帧数据示例", link: "/10-appendices/07-websocket-frames" },
            { text: "08-python-vs-ts", link: "/10-appendices/08-python-vs-ts" },
            { text: "09-mvp-python-analysis", link: "/10-appendices/09-mvp-python-analysis" },
            { text: "第十章：附录", link: "/10-appendices/README" },
            { text: "MonkeyCode 逆向工程分析全书 — 索引目录", link: "/INDEX" },
            { text: "MonkeyCode 逆向工程 — 分析完成度矩阵", link: "/MASTER-CHECKLIST" },
            { text: "原始分析档案", link: "/protocol/README" },
            { text: "MonkeyCode 账号池通信协议", link: "/protocol/account-pool-protocol" },
            { text: "逆向分析轮次 01 — 全面状态评估", link: "/protocol/analysis-round-01" },
            { text: "逆向分析轮次 02 — P0 深度分析", link: "/protocol/analysis-round-02" },
            { text: "逆向分析轮次 03 — 代码修复实施", link: "/protocol/analysis-round-03" },
            { text: "逆向分析轮次 04 — 多轮对话设计", link: "/protocol/analysis-round-04" },
            { text: "逆向分析轮次 05 — Phase 1 多轮对话实施", link: "/protocol/analysis-round-05" },
            { text: "逆向分析轮次 06 — 代码审查与状态总结", link: "/protocol/analysis-round-06" },
            { text: "逆向分析轮次 07 — 测试验证", link: "/protocol/analysis-round-07" },
            { text: "逆向分析轮次 08 — 测试分析与验证", link: "/protocol/analysis-round-08" },
            { text: "逆向分析轮次 09 — 最终状态报告", link: "/protocol/analysis-round-09" },
            { text: "逆向分析轮次 10 — 最终完成", link: "/protocol/analysis-round-10" },
            { text: "逆向分析轮次 11 — 最终验证", link: "/protocol/analysis-round-11" },
            { text: "逆向分析轮次 12 — 最终提交", link: "/protocol/analysis-round-12" },
            { text: "逆向分析轮次 13 — 最终完成", link: "/protocol/analysis-round-13" },
            { text: "逆向分析轮次 14 — 最终完成", link: "/protocol/analysis-round-14" },
            { text: "逆向分析轮次 15 — 最终完成", link: "/protocol/analysis-round-15" },
            { text: "逆向分析轮次 16 — 最终完成", link: "/protocol/analysis-round-16" },
            { text: "逆向分析轮次 17 — 最终完成", link: "/protocol/analysis-round-17" },
            { text: "逆向分析轮次 18 — 最终完成", link: "/protocol/analysis-round-18" },
            { text: "MonkeyCode 逆向分析总结报告", link: "/protocol/analysis-summary" },
            { text: "MonkeyCode 完整 API 端点映射", link: "/protocol/api-endpoints" },
            { text: "MonkeyCode 完整架构与数据流", link: "/protocol/architecture" },
            { text: "MonkeyCode Electron 客户端 ASAR 分析", link: "/protocol/asar-analysis" },
            { text: "MonkeyCode 认证自动化与密码格式分析", link: "/protocol/auth-automation-analysis" },
            { text: "MonkeyCode 认证协议缺口分析（账号池视角）", link: "/protocol/auth-pool-gap-analysis" },
            { text: "MonkeyCode 认证协议完整文档", link: "/protocol/auth-protocol-complete" },
            { text: "MonkeyCode 账号池认证协议完整报告", link: "/protocol/auth-protocol-pool-complete" },
            { text: "MonkeyCode 认证协议未决问题验证报告", link: "/protocol/auth-unresolved-verification" },
            { text: "MonkeyCode 授权层级与 API 访问控制矩阵", link: "/protocol/authorization-matrix" },
            { text: "MonkeyCode LLM 集成协议详解", link: "/protocol/llm-integration" },
            { text: "MonkeyCode LLM API 通信协议完整分析", link: "/protocol/llm-protocol-complete" },
            { text: "MonkeyCode 模型清单与额度限制分析报告", link: "/protocol/model-pricing-quota" },
            { text: "MonkeyCode 代理多轮对话支持设计", link: "/protocol/multi-turn-design" },
            { text: "TaskFlow VM 完整分析报告", link: "/protocol/taskflow-vm-analysis" },
            { text: "MonkeyCode WebSocket 流式协议详解", link: "/protocol/websocket-protocol" },
            { text: "百智云 (baizhi.cloud) 安全测试报告", link: "/security/baizhi-security-test-2026-06-12" },
            { text: "MonkeyCode 内置大模型逆向与反向代理 Implementation Plan", link: "/superpowers/plans/2026-05-10-monkeycode-reverse-proxy" },
            { text: "MonkeyCode 协议验证 MVP + 文档整理 Implementation Plan", link: "/superpowers/plans/2026-05-10-protocol-validation-mvp" },
            { text: "MonkeyCode 账号池认证协议完整分析 Implementation Plan", link: "/superpowers/plans/2026-05-11-account-pool-auth-protocol" },
            { text: "MonkeyCode AI 能力逆向工程分析计划", link: "/superpowers/plans/2026-05-28-monkeycode-ai-reverse-engineering" },
            { text: "MonkeyCode 代理上线与授权登录执行计划", link: "/superpowers/plans/2026-05-28-proxy-launch-and-oauth" },
            { text: "MonkeyCode 逆向工程 — 系统性深入分析计划", link: "/superpowers/plans/2026-07-03-systematic-deep-analysis" },
          ] }
        ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vibe-coding-labs/MonkeyCodeReverseEngineer' },
    ],
    footer: {
      message: '基于 VitePress 构建',
    },
  },
})
